# Generated by Django 2.2.24 on 2021-06-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_сomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сomments',
            name='title',
        ),
    ]
