# Generated by Django 2.2.24 on 2021-06-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subсomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='сomments',
            name='comment',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
