# Generated by Django 2.2.24 on 2021-06-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_сomments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сomments',
            name='comment',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
