# Generated by Django 2.2.24 on 2021-06-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210625_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сomments',
            name='comment',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
