# Generated by Django 2.2.24 on 2021-06-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210625_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сomments',
            name='comment',
            field=models.SmallIntegerField(null=True),
        ),
    ]
