# Generated by Django 2.2.24 on 2021-06-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_сomments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='сomments',
            name='levels',
            field=models.SmallIntegerField(null=True),
        ),
    ]
