# Generated by Django 2.2.24 on 2021-06-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_сomments_levels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubСomments',
        ),
    ]
